# Site settings
title: Digital Rain Modern C++ Project Blog
author:
  name: Rakib Rana
  email: G00408***@atu.ie
description: "A comprehensive blog detailing the development and insights of the Digital Rain project using Modern C++."

# Build settings
remote_theme: jekyll-theme-minimal
theme: jekyll-theme-minimal

