# Site settings
title: Matrix Digital Rain in Modern C++
author:
  name: Rakib Rana
  email: G00408***@atu.ie
description: "A comprehensive showcase of the Matrix Digital Rain animation project created using Modern C++ and Windows Console API."

# Build settings
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme

# GitHub metadata
github:
  is_project_page: true
  repository_url: https://github.com/RakibR7/Matrix-Rain-cpp

# Page settings
show_downloads: true
