# Site settings
title: Matrix Digital Rain in Modern C++
author:
  name: Rakib Rana
  email: G00408***@atu.ie
description: "A comprehensive showcase of the Matrix Digital Rain animation project created using Modern C++ and Windows Console API."

# Build settings
remote_theme: jekyll-theme-minimal
theme: jekyll-theme-minimal

# GitHub metadata
github:
  is_project_page: true
  repository_url: https://github.com/RakibR7/Matrix-Rain-cpp

# Page settings
show_downloads: true
logo: https://raw.githubusercontent.com/RakibR7/Matrix-Rain-cpp/main/docs/assets/images/main_part_3.png
